### ISSUE TITLE
the Package named NAR_pytorch is not found

### ISSUE THREAD

**Issue by jingchao1965** [taodav/novelty-search-repr-space#2]
In the file named 'run_se_maze.py' which is under the folder named pycolab,I don't find the package named NAR_pytorch.

**Comment by 15210579725** [comment]
thanks for your excellent work！ I also meet this problem when I was trying to reproduce this work. 
It would be great if taodav could upload this file~
![image](https://github.com/taodav/nsrs/assets/136165406/1b34e4f6-1702-4f02-9f9f-14035feffc01)
@taodav

**Comment by taodav** [comment]
Hi everyone, I've uploaded commit that points NAR_pytorch to the right file. I renamed the NAR algo to the NSRS algo in the work, and forgot to change the name.

For future reference, this codebase is not maintained!
